version: '3.8'

services:
  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - back
    ports:
      - "8282:80"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./:/var/www/html

  back:
    image: chialab/php:8.0-fpm
    restart: always
    volumes:
      - ./:/var/www/html

  db:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/db:/var/lib/mysql

  dbadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    ports:
      - "8080:80"

